Non Personalised Recommender System

In [2]:
import pandas as pd
import numpy as np

Ratings=pd.read_csv("ml-latest/ratings.csv")
Movies=pd.read_csv("ml-latest/movies.csv")
Tags=pd.read_csv("ml-latest/tags.csv")

Ratings_mean=Ratings.groupby(['movieId'])[['rating']].mean().rename(columns = {'rating': 'Mean_rating'}).reset_index()
# Calculating damped mean using alpha = 5

Ratings_sum=Ratings.groupby(['movieId'])[['rating']].sum().rename(columns = {'rating': 'sum_rating'}).reset_index()
Ratings_sum['sum_rating_factor']=Ratings_sum['sum_rating']+5*(Ratings['rating'].mean())
Ratings_count=Ratings.groupby(['movieId'])[['rating']].count().rename(columns = {'rating': 'count_rating'}).reset_index()

Ratings_count['count_rating_factor']=Ratings_count['count_rating']+5
Ratings_damped=pd.merge(Ratings_sum,Ratings_count[['movieId','count_rating','count_rating_factor']],on=['movieId'],how='left')
Ratings_damped['damped_mean']=Ratings_damped['sum_rating_factor']/Ratings_damped['count_rating_factor']
Ratings_mean_dampmean=pd.merge(Ratings_mean[['movieId','Mean_rating']],Ratings_damped[['movieId','damped_mean']],on=['movieId'],how='left')

# Sorting to get top rated movies

Ratings_mean_dampmean = Ratings_mean_dampmean.sort_values(['Mean_rating'], ascending=False)

In [3]:
Ratings_mean_dampmean

       movieId  Mean_rating  damped_mean
34799   147966          5.0     3.773409
37018   154341          5.0     3.773409
40487   164620          5.0     3.773409
41457   167134          5.0     3.773409
28386   129223          5.0     3.773409
34481   146946          5.0     3.773409
28380   129197          5.0     3.773409
44881   175737          5.0     3.773409
9568     27914          5.0     3.773409
32543   141434          5.0     3.773409
28370   129076          5.0     3.773409
28357   129036          5.0     3.773409
40453   164542          5.0     3.773409
40400   164371          5.0     3.773409
40380   164278          5.0     3.773409
28245   128713          5.0     3.773409
34674   147402          5.0     3.773409
23590   111546          5.0     3.773409
23591   111548          5.0     3.773409
25789   119810          5.0     3.773409
32488   141297          5.0     3.773409
32484   141275          5.0     3.773409
34683   147430          5.0     3.773409
38650   159123          5.0     3.773409
30172   134633          5.0     3.773409
40327   164165          5.0     3.948636
32424   141064          5.0     3.773409
44879   175733          5.0     3.773409
34386   146650          5.0     3.773409
38043   157565          5.0     3.773409
...        ...          ...          ...
37594   155963          0.5     3.023409
37593   155961          0.5     3.023409
37592   155959          0.5     3.023409
37590   155954          0.5     3.023409
37589   155952          0.5     3.023409
29811   133638          0.5     3.023409
29810   133632          0.5     3.023409
37582   155910          0.5     3.023409
23444   110800          0.5     3.023409
23445   110802          0.5     3.023409
37643   156133          0.5     3.023409
37647   156150          0.5     3.023409
37721   156611          0.5     3.023409
37648   156152          0.5     3.023409
30086   134395          0.5     3.023409
30012   134198          0.5     3.023409
19014    94308          0.5     3.023409
37686   156539          0.5     3.023409
44615   174915          0.5     3.023409
29968   134081          0.5     3.023409
19020    94327          0.5     3.023409
19021    94337          0.5     3.023409
29955   134037          0.5     3.023409
5707      5805          0.5     2.662922
29925   133941          0.5     2.662922
29904   133871          0.5     3.023409
44626   174947          0.5     3.023409
29880   133810          0.5     3.023409
37649   156154          0.5     3.023409
43044   171217          0.5     3.023409

[45115 rows x 3 columns]

Below is the code to implement Basic association rule Recommender System.

In [9]:
movie_association = pd.DataFrame(columns=['movieId','movieId1','association'])
distinct_movies=np.unique(Ratings['movieId'])
i=1
for movie in distinct_movies[157:158]:
    movie_data=Ratings[Ratings['movieId']==movie]
    print("movie: ", i , "out of: ", len(distinct_movies))
    j=1 
    for movie1 in distinct_movies:
 
        movie1_data=Ratings[Ratings['movieId']==movie1]
        distinct_cust=len(np.unique(movie_data['userId']))
        movie2_data=movie1_data[movie1_data['userId'].isin(np.unique([movie_data['userId']]))]
        distinct_cust_common=len(np.unique(movie2_data['userId']))
        fraction_common_cust=float(distinct_cust_common)/float(distinct_cust)
 
        movie_temp=pd.DataFrame(columns=["movieId","movieId1","association"])
        movie_temp = movie_temp.append({ "movieId": movie, "movieId1": movie1,"association": fraction_common_cust}, 
                                       ignore_index=True)
 
        movie_association = movie_association.append(movie_temp, ignore_index=True)
        if j%500==0:
            print (j)
        j=j+1
    i=i+1
    movie_association=movie_association.sort_index(by=["movieId","association"]).reset_index()

movie:  1 out of:  45115
500
1000
1500
2000
2500
3000
3500
4000
4500
5000
5500
6000
6500
7000
7500
8000
8500
9000
9500
10000
10500
11000
11500
12000
12500
13000
13500
14000
14500
15000
15500
16000
16500
17000
17500
18000
18500
19000
19500
20000
20500
21000
21500
22000
22500
23000
23500
24000
24500
25000
25500
26000
26500
27000
27500
28000
28500
29000
29500
30000
30500
31000
31500
32000
32500
33000
33500
34000
34500
35000
35500
36000
36500
37000
37500
38000
38500
39000
39500
40000
40500
41000
41500
42000
42500
43000
43500
44000
44500
45000

C:\Users\lalwa\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: by argument to sort_index is deprecated, please use .sort_values(by=...)

In [10]:
movie_association

       index  movieId  movieId1  association
0       1509    159.0    1559.0     0.000000
1       1517    159.0    1568.0     0.000000
2       1526    159.0    1578.0     0.000000
3       1649    159.0    1708.0     0.000000
4       1650    159.0    1709.0     0.000000
5       1678    159.0    1740.0     0.000000
6       1696    159.0    1764.0     0.000000
7       1749    159.0    1830.0     0.000000
8       1765    159.0    1847.0     0.000000
9       1769    159.0    1851.0     0.000000
10      2167    159.0    2251.0     0.000000
11      2517    159.0    2601.0     0.000000
12      2535    159.0    2619.0     0.000000
13      2873    159.0    2958.0     0.000000
14      2994    159.0    3080.0     0.000000
15      3107    159.0    3193.0     0.000000
16      3140    159.0    3226.0     0.000000
17      3192    159.0    3278.0     0.000000
18      3204    159.0    3290.0     0.000000
19      3270    159.0    3356.0     0.000000
20      3471    159.0    3561.0     0.000000
21      3492    159.0    3582.0     0.000000
22      3764    159.0    3856.0     0.000000
23      3812    159.0    3904.0     0.000000
24      3982    159.0    4075.0     0.000000
25      4077    159.0    4170.0     0.000000
26      4361    159.0    4455.0     0.000000
27      4362    159.0    4456.0     0.000000
28      4554    159.0    4648.0     0.000000
29      4725    159.0    4820.0     0.000000
...      ...      ...       ...          ...
45085    250    159.0     253.0     0.630187
45086      5    159.0       6.0     0.631408
45087     15    159.0      16.0     0.632628
45088    151    159.0     153.0     0.641579
45089    257    159.0     260.0     0.650122
45090    450    159.0     454.0     0.651749
45091    163    159.0     165.0     0.652563
45092    340    159.0     344.0     0.652970
45093    297    159.0     300.0     0.661107
45094    285    159.0     288.0     0.672498
45095     20    159.0      21.0     0.703824
45096    523    159.0     527.0     0.713995
45097    602    159.0     608.0     0.729455
45098    108    159.0     110.0     0.731489
45099    376    159.0     380.0     0.737592
45100    584    159.0     590.0     0.737998
45101    583    159.0     589.0     0.740033
45102    373    159.0     377.0     0.740439
45103     31    159.0      32.0     0.757933
45104    476    159.0     480.0     0.771359
45105     46    159.0      47.0     0.783564
45106    586    159.0     592.0     0.786819
45107    148    159.0     150.0     0.790480
45108    352    159.0     356.0     0.797396
45109    453    159.0     457.0     0.813263
45110     49    159.0      50.0     0.832791
45111    315    159.0     318.0     0.842962
45112    587    159.0     593.0     0.846623
45113    293    159.0     296.0     0.923922
45114    157    159.0     159.0     1.000000

[45115 rows x 4 columns]

Below is the code to implement Lift based Recommender System.

In [ ]:
movie_association = pd.DataFrame(columns=['movieId','movieId1','association'])

distinct_movies=np.unique(Ratings['movieId'])
i=1
for movie in distinct_movies[1284:1285]:
     movie_data=Ratings[Ratings['movieId']==movie]
     print ("movie: ", i , "out of: ", len(distinct_movies))
     j=1 b
     for movie1 in distinct_movies:
 
         movie1_data=Ratings[Ratings["movieId"]==movie1]
         distinct_cust=len(np.unique(movie_data['userId']))
         distinct_cust1=len(np.unique(movie1_data['userId']))
         movie2_data=movie1_data[movie1_data['userId'].isin(np.unique([movie_data['userId']]))]
         distinct_cust_common=len(np.unique(movie2_data['userId']))
         fraction_common_cust=(float(distinct_cust_common)*len(np.unique(Ratings['userId'])))/(float(distinct_cust)*float(distinct_cust1))
 
         movie_temp=pd.DataFrame(columns=['movieId','movieId1','association])
         movie_temp = movie_temp.append({ "movieId": movie, "movieId1": movie1, "association": fraction_common_cust},
                                        ignore_index=True)
 
 
         movie_association = movie_association.append(movie_temp, ignore_index=True)
         if j%500==0:
             print (j)
         j=j+1
     i=i+1
     movie_association=movie_association.sort_index(by=['movieId','association']).reset_index()